apiVersion: v1
kind: Service
metadata:
  name: "{name}"
  namespace: "{namespace}"
spec:
  clusterIP: None
  ports:
  - port: 6379
    name: redis
  - port: 16379
    name: cluster
  selector:
    app: "{labels[app]}"
    component: "{sts_name}"
    environment: "{labels[environment]}"